### ISSUE TITLE
[Suggestion/Question] Worldspace UI and VR Interaction support

### ISSUE THREAD

**Issue by Vin-meido** [sinai-dev/UniverseLib#4]
Would it be possible to implement a method for registering UIs as Worldspace?

After which, would it be possible to have an alternate InputModule that's based on Physics.Raycast'ing from a specific game object (e.g. either camera, or a hand object). This would be mostly useful when making plugin UIs that you can access via VR.

Or would this be out of scope of the library?

**Comment by sinai-dev** [comment]
I guess it should be possible if we leave it up to the person registering the UI to provide their own VR input module, shouldn't be too hard to add support for that. If you think that would work I can look into it for you.

**Comment by Vin-meido** [comment]
Hmm does this mean you'd want the VR input module be the concern of the plugin author that's registering the UI?

What I was more wondering is if you'd be able to look into implementing such a vr support module from within the library - so that if you have, for example, a collection of plugins depending on the library, and the game they're all running on is in VR mode, then interacting with them would be possible within the VR environment. This includes, but is not limited to having gaze input (via camera object), or pointer input via a hand object.

I guess every game would be different in this regard though, so this can't be implemented as part of library... But just checking just in case you have ideas on how you can make this easier to support on every game.

**Comment by sinai-dev** [comment]
> I guess every game would be different in this regard though, so this can't be implemented as part of library.

This is my understanding, I'm not that knowledgable about it but from what I have been told there are many different ways of handling VR input, a lot of games even make their own custom implementation, so I dont think its practical. If it can be demonstrated that this is not true I'd be happy to be proven wrong, but otherwise yeah its gonna have to be up to mod authors to handle it, perhaps each community could have a plugin for UniverseLib or something.
